-- Fix categories to have exactly 9 categories as specified in categories.md
-- Clear existing categories and insert the correct 9 categories

-- First, clear existing categories
DELETE FROM public.categories;

-- Insert the 9 main categories from categories.md
INSERT INTO public.categories (slug, locale, name, description, content, icon_name, color_theme, sort_order, is_active) VALUES
-- 1. Nature & Adventure
('nature', 'en', 'Nature & Adventure', 'Discover the pure power of nature on trails rising from valleys to Kaçkar''s peaks.', '{"header": "Discover the Untamed Beauty of Kaçkar Mountains", "bullets": ["Over 50 pristine alpine lakes", "3,937m highest peak - Kaçkar Dağı", "Endemic flora and fauna", "Ancient forests and meadows", "Crystal clear mountain streams"], "body": "The Kaçkar Mountains offer an unparalleled natural experience with their pristine wilderness, glacial lakes, and diverse ecosystems. From the highest peak at 3,937 meters to the crystal-clear alpine lakes, every corner of this region tells a story of natural wonder."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 1, true),
('nature', 'tr', 'Doğa & Macera', 'Kaçkar''ın vadilerinden zirvelerine uzanan patikalarda doğanın saf gücünü keşfedin.', '{"header": "Kaçkar Dağları''nın Vahşi Güzelliğini Keşfedin", "bullets": ["50''den fazla pristine alpine göl", "3,937m en yüksek zirve - Kaçkar Dağı", "Endemik flora ve fauna", "Antik ormanlar ve çayırlar", "Kristal berraklığında dağ dereleri"], "body": "Kaçkar Dağları, pristine vahşi doğası, buzul gölleri ve çeşitli ekosistemleri ile eşsiz bir doğa deneyimi sunar. 3,937 metre yüksekliğindeki en yüksek zirveden kristal berraklığındaki alpine göllere kadar, bu bölgenin her köşesi doğal harikaların hikayesini anlatır."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 1, true),

-- 2. Culture & Local Life
('culture', 'en', 'Culture & Local Life', 'Witness the heartfelt stories of highlands, mansions and timeless traditions.', '{"header": "Immerse Yourself in Ancient Traditions", "bullets": ["Traditional Laz and Hemshin communities", "Ancient monasteries and churches", "Local handicrafts and textiles", "Traditional music and dance", "Authentic village life"], "body": "The Kaçkar region is a cultural treasure trove where ancient traditions have been preserved for centuries. The local Laz and Hemshin communities maintain their unique customs, language, and way of life."}', 'Users', 'from-[#0E4542] to-[#0E4542]', 2, true),
('culture', 'tr', 'Kültür & Yerel Hayat', 'Yaylaların, konakların ve köklü geleneklerin içten hikâyesine tanık olun.', '{"header": "Antik Geleneklerin İçine Dalın", "bullets": ["Geleneksel Laz ve Hemşin toplulukları", "Antik manastırlar ve kiliseler", "Yerel el sanatları ve tekstiller", "Geleneksel müzik ve dans", "Otantik köy yaşamı"], "body": "Kaçkar bölgesi, antik geleneklerin yüzyıllardır korunduğu kültürel bir hazine sandığıdır. Yerel Laz ve Hemşin toplulukları, benzersiz geleneklerini, dillerini ve yaşam tarzlarını sürdürürler."}', 'Users', 'from-[#0E4542] to-[#0E4542]', 2, true),

-- 3. Gastronomy & Local Flavours
('gastronomy', 'en', 'Gastronomy & Local Flavours', 'Taste Kaçkar through its GI products and unforgettable local flavours.', '{"header": "Savor the Authentic Flavors of Black Sea Cuisine", "bullets": ["Fresh mountain trout and seafood", "Traditional corn bread and local cheeses", "Organic honey and mountain herbs", "Traditional tea ceremonies", "Local wine and spirits"], "body": "The culinary traditions of the Kaçkar region reflect the unique blend of mountain and coastal influences. Fresh ingredients from the mountains and the Black Sea create a distinctive cuisine that has been perfected over generations."}', 'ForkKnife', 'from-[#0E4542] to-[#0E4542]', 3, true),
('gastronomy', 'tr', 'Gastronomi & Yerel Lezzetler', 'Coğrafi işaretli ürünler ve unutulmaz lezzetlerle Kaçkar''ın tadına varın.', '{"header": "Karadeniz Mutfağının Otantik Lezzetlerini Tadın", "bullets": ["Taze dağ alabalığı ve deniz ürünleri", "Geleneksel mısır ekmeği ve yerel peynirler", "Organik bal ve dağ otları", "Geleneksel çay seremonileri", "Yerel şarap ve içkiler"], "body": "Kaçkar bölgesinin mutfak gelenekleri, dağ ve kıyı etkilerinin benzersiz karışımını yansıtır. Dağlardan ve Karadeniz''den taze malzemeler, nesiller boyunca mükemmelleştirilmiş ayırt edici bir mutfak yaratır."}', 'ForkKnife', 'from-[#0E4542] to-[#0E4542]', 3, true),

-- 4. Music & Dance
('music-dance', 'en', 'Music & Dance', 'Feel the Black Sea''s spirit with the tulum''s sound and horon''s rhythm.', '{"header": "Feel the Black Sea''s Spirit", "bullets": ["Traditional tulum and kemençe performances", "Various horon dance styles", "Instrument making workshops", "Festival and wedding traditions", "Cultural music experiences"], "body": "The soul of the Black Sea lives in the vibrant tunes of tulum and kemençe. Horon dance chains embody the region''s energy from weddings to highland festivals."}', 'MusicNote', 'from-[#0E4542] to-[#0E4542]', 4, true),
('music-dance', 'tr', 'Müzik & Dans', 'Tulumun sesi ve horonun ritmiyle Karadeniz''in ruhunu hissedin.', '{"header": "Karadeniz''in Ruhunu Hissedin", "bullets": ["Geleneksel tulum ve kemençe dinletileri", "Çeşitli horon dans türleri", "Çalgı yapımı atölyeleri", "Şenlik ve düğün gelenekleri", "Kültürel müzik deneyimleri"], "body": "Karadeniz''in ruhu, tulum ve kemençenin coşkulu ezgilerinde hayat bulur. Horon zincirleri, düğünlerden yayla şenliklerine kadar bölgenin enerjisini yansıtır."}', 'MusicNote', 'from-[#0E4542] to-[#0E4542]', 4, true),

-- 5. Sustainable Tourism
('sustainable-tourism', 'en', 'Sustainable Tourism', 'A journey of discovery that respects nature and supports local life.', '{"header": "Respectful and Sustainable Exploration", "bullets": ["Leave no trace principles", "Local producer support", "Eco-friendly accommodation", "Eco-tourism routes", "Nature conservation projects"], "body": "Explore Kaçkar in a way that preserves its natural beauty for future generations. Our sustainable tourism approach ensures that your visit benefits local communities while protecting the environment."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 5, true),
('sustainable-tourism', 'tr', 'Sürdürülebilir Turizm', 'Doğaya saygılı, yerel halka faydalı bir keşif yolculuğu.', '{"header": "Saygılı ve Sürdürülebilir Keşif", "bullets": ["İz bırakmama ilkeleri", "Yerel üretici desteği", "Çevre dostu konaklama", "Eko-turizm rotaları", "Doğa koruma projeleri"], "body": "Kaçkar''ı gelecek nesiller için doğal güzelliğini koruyacak şekilde keşfedin. Sürdürülebilir turizm yaklaşımımız, ziyaretinizin çevreyi korurken yerel topluluklara fayda sağlamasını garanti eder."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 5, true),

-- 6. Health & Wellness
('health-wellness', 'en', 'Health & Wellness', 'Refresh your body and soul in the clear air of the highlands.', '{"header": "Rejuvenate in Nature''s Embrace", "bullets": ["Yoga and meditation in highlands", "Breathing therapy camps", "Natural healing workshops", "Thermal springs at Ayder", "Wellness retreats"], "body": "The pristine air and natural beauty of the Kaçkar highlands provide the perfect setting for wellness and healing. Experience traditional and modern wellness practices in harmony with nature."}', 'Heart', 'from-[#0E4542] to-[#0E4542]', 6, true),
('health-wellness', 'tr', 'Sağlık & Wellness', 'Yaylaların temiz havasında ruhunuzu ve bedeninizi yenileyin.', '{"header": "Doğanın Kucağında Yenilenin", "bullets": ["Yaylalarda yoga ve meditasyon", "Nefes terapisi kampları", "Doğal şifa atölyeleri", "Ayder kaplıcaları", "Wellness tatilleri"], "body": "Kaçkar yaylalarının temiz havası ve doğal güzelliği, wellness ve şifa için mükemmel bir ortam sağlar. Doğayla uyum içinde geleneksel ve modern wellness uygulamalarını deneyimleyin."}', 'Heart', 'from-[#0E4542] to-[#0E4542]', 6, true),

-- 7. Photography & Art
('photography-art', 'en', 'Photography & Art', 'Capture unique landscapes shaped by the light of the seasons.', '{"header": "Capture Unique Landscapes", "bullets": ["Seasonal photography routes", "Artist workshops & open-air exhibitions", "Artist-in-residence programs", "Nature-inspired art", "Photography expeditions"], "body": "The changing light and seasons of Kaçkar create endless opportunities for artistic expression. From seasonal photography routes to artist workshops, discover the creative side of this magnificent landscape."}', 'Camera', 'from-[#0E4542] to-[#0E4542]', 7, true),
('photography-art', 'tr', 'Fotoğraf & Sanat', 'Mevsimlerin ışığıyla şekillenen eşsiz manzaraları yakalayın.', '{"header": "Eşsiz Manzaraları Yakalayın", "bullets": ["Mevsimsel fotoğraf rotaları", "Sanatçı atölyeleri & açık hava sergileri", "Artist-in-residence programları", "Doğadan ilham alan sanat", "Fotoğraf keşif gezileri"], "body": "Kaçkar''ın değişen ışığı ve mevsimleri, sanatsal ifade için sınırsız fırsatlar yaratır. Mevsimsel fotoğraf rotalarından sanatçı atölyelerine kadar, bu muhteşem manzaranın yaratıcı yanını keşfedin."}', 'Camera', 'from-[#0E4542] to-[#0E4542]', 7, true),

-- 8. Educational & Research Tourism
('educational-research', 'en', 'Educational & Research Tourism', 'A living laboratory stretching from endemic plants to glacial lakes.', '{"header": "Explore a Living Laboratory", "bullets": ["Biology & botany observation tours", "Birdwatching expeditions", "Geology & glacier lake research", "Craftsmanship training programs", "Scientific research opportunities"], "body": "Kaçkar serves as a natural laboratory for researchers and students. From endemic plants to glacial lakes, the region offers unique opportunities for educational and scientific exploration."}', 'GraduationCap', 'from-[#0E4542] to-[#0E4542]', 8, true),
('educational-research', 'tr', 'Eğitim & Araştırma Turizmi', 'Endemik bitkilerden buzul göllerine uzanan canlı bir laboratuvar.', '{"header": "Canlı Bir Laboratuvarı Keşfedin", "bullets": ["Biyoloji & botanik gözlem turları", "Kuş gözlemi keşif gezileri", "Jeoloji & buzul gölü araştırmaları", "Zanaat eğitim programları", "Bilimsel araştırma fırsatları"], "body": "Kaçkar, araştırmacılar ve öğrenciler için doğal bir laboratuvar görevi görür. Endemik bitkilerden buzul göllerine kadar, bölge eğitim ve bilimsel keşif için benzersiz fırsatlar sunar."}', 'GraduationCap', 'from-[#0E4542] to-[#0E4542]', 8, true),

-- 9. Events & Festivals
('events-festivals', 'en', 'Events & Festivals', 'Join vibrant celebrations from highland festivals to tea harvests.', '{"header": "Join Vibrant Celebrations", "bullets": ["Highland festivals", "Horon festivals", "Tea harvest festival", "Local product markets", "Cultural celebrations"], "body": "Throughout the year, Kaçkar comes alive with festivals and celebrations that showcase the region''s rich culture. From highland festivals to tea harvest celebrations, experience the vibrant spirit of local traditions."}', 'CalendarCheck', 'from-[#0E4542] to-[#0E4542]', 9, true),
('events-festivals', 'tr', 'Etkinlik & Festivaller', 'Yayla şenliklerinden çay hasadına, coşkulu kutlamalara katılın.', '{"header": "Coşkulu Kutlamalara Katılın", "bullets": ["Yayla şenlikleri", "Horon festivalleri", "Çay hasadı festivali", "Yerel ürün pazarları", "Kültürel kutlamalar"], "body": "Yıl boyunca Kaçkar, bölgenin zengin kültürünü sergileyen festivaller ve kutlamalarla canlanır. Yayla şenliklerinden çay hasadı kutlamalarına kadar, yerel geleneklerin coşkulu ruhunu deneyimleyin."}', 'CalendarCheck', 'from-[#0E4542] to-[#0E4542]', 9, true);
