-- Add missing French and German categories to complete the 9 categories
-- This migration adds the remaining 3 categories that were missing from the previous migration

-- Add missing French categories
INSERT INTO public.categories (slug, locale, name, description, content, icon_name, color_theme, sort_order, is_active) VALUES
('music-dance', 'fr', 'Musique & Danse', 'Ressentez l''esprit de la mer Noire avec le son du tulum et le rythme du horon.', '{"header": "Ressentez l''Esprit de la Mer Noire", "bullets": ["Variétés de danse horon", "Performances de tulum et kemençe", "Ateliers de fabrication d''instruments", "Festivals et traditions de mariage", "Célébrations culturelles vibrantes"], "body": "La musique et la danse sont au cœur de la culture de la région de Kaçkar. Le tulum et le kemençe créent des mélodies envoûtantes qui captent l''essence de la mer Noire, tandis que les danses horon énergiques expriment la joie et l''unité de la communauté."}', 'MusicNote', 'from-[#0E4542] to-[#0E4542]', 7, true),
('sustainable-tourism', 'fr', 'Tourisme Durable', 'Un voyage de découverte qui respecte la nature et soutient la vie locale.', '{"header": "Explorez de Manière Responsable", "bullets": ["Principes de ne laisser aucune trace", "Soutien aux producteurs locaux", "Hébergement respectueux de l''environnement", "Routes d''écotourisme", "Projets de conservation"], "body": "Le tourisme durable dans la région de Kaçkar signifie voyager de manière responsable, en minimisant l''impact sur l''environnement et en maximisant les bénéfices pour les communautés locales. Découvrez comment explorer cette région magnifique tout en préservant sa beauté naturelle pour les générations futures."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 8, true),
('health-wellness', 'fr', 'Santé & Bien-être', 'Rafraîchissez votre corps et votre âme dans l''air pur des hautes terres.', '{"header": "Retrouvez l''Équilibre dans la Nature", "bullets": ["Yoga et méditation en altitude", "Thérapie respiratoire", "Ateliers de guérison naturelle", "Sources thermales d''Ayder", "Retraites de bien-être"], "body": "Les hautes terres de Kaçkar offrent l''environnement parfait pour la relaxation et la guérison. L''air pur de montagne, les sources thermales naturelles et la tranquillité de la nature créent un sanctuaire idéal pour retrouver l''équilibre physique et mental."}', 'Heart', 'from-[#0E4542] to-[#0E4542]', 9, true),
('photography-art', 'fr', 'Photographie & Art', 'Capturez des paysages uniques façonnés par la lumière des saisons.', '{"header": "Créez de l''Art dans la Nature", "bullets": ["Routes photographiques saisonnières", "Ateliers d''artistes", "Expositions en plein air", "Programmes de résidence d''artistes", "Inspiration naturelle"], "body": "Les montagnes de Kaçkar offrent une toile infinie pour les artistes et photographes. Chaque saison apporte sa propre palette de couleurs et d''émotions, des fleurs sauvages du printemps aux paysages enneigés de l''hiver, créant des opportunités artistiques uniques."}', 'Camera', 'from-[#0E4542] to-[#0E4542]', 10, true),
('educational-research', 'fr', 'Tourisme Éducatif & Recherche', 'Un laboratoire vivant s''étendant des plantes endémiques aux lacs glaciaires.', '{"header": "Apprenez dans un Laboratoire Naturel", "bullets": ["Tours de biologie et botanique", "Observation d''oiseaux", "Recherche géologique et glaciaire", "Programmes d''éducation artisanale", "Études environnementales"], "body": "La région de Kaçkar sert de laboratoire naturel pour l''éducation et la recherche. Avec sa biodiversité unique, ses formations géologiques fascinantes et ses écosystèmes préservés, c''est un endroit idéal pour apprendre et découvrir les merveilles de la nature."}', 'BookOpen', 'from-[#0E4542] to-[#0E4542]', 11, true),
('events-festivals', 'fr', 'Événements & Festivals', 'Rejoignez des célébrations vibrantes des festivals des hautes terres aux récoltes de thé.', '{"header": "Célébrez avec la Communauté", "bullets": ["Festivals des hautes terres", "Festivals de danse horon", "Festival de récolte du thé", "Marchés de produits locaux", "Journées gastronomiques"], "body": "Les événements et festivals de Kaçkar sont des célébrations vivantes de la culture locale. Des festivals des hautes terres animés aux récoltes de thé traditionnelles, ces événements offrent une chance unique de s''immerger dans la vie communautaire et les traditions locales."}', 'Calendar', 'from-[#0E4542] to-[#0E4542]', 12, true)
ON CONFLICT (slug, locale) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  content = EXCLUDED.content,
  icon_name = EXCLUDED.icon_name,
  color_theme = EXCLUDED.color_theme,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

-- Add missing German categories
INSERT INTO public.categories (slug, locale, name, description, content, icon_name, color_theme, sort_order, is_active) VALUES
('music-dance', 'de', 'Musik & Tanz', 'Fühlen Sie den Geist des Schwarzen Meeres mit dem Klang des Tulum und dem Rhythmus des Horon.', '{"header": "Fühlen Sie den Geist des Schwarzen Meeres", "bullets": ["Horon-Tanz-Variationen", "Tulum- und Kemençe-Aufführungen", "Instrumentenbau-Workshops", "Festivals und Hochzeitstraditionen", "Lebendige kulturelle Feiern"], "body": "Musik und Tanz stehen im Herzen der Kultur der Kaçkar-Region. Tulum und Kemençe schaffen bezaubernde Melodien, die das Wesen des Schwarzen Meeres einfangen, während die energischen Horon-Tänze die Freude und Einheit der Gemeinschaft ausdrücken."}', 'MusicNote', 'from-[#0E4542] to-[#0E4542]', 7, true),
('sustainable-tourism', 'de', 'Nachhaltiger Tourismus', 'Eine Entdeckungsreise, die die Natur respektiert und das lokale Leben unterstützt.', '{"header": "Erkunden Sie Verantwortungsvoll", "bullets": ["Leave-No-Trace-Prinzipien", "Unterstützung lokaler Produzenten", "Umweltfreundliche Unterkünfte", "Ökotourismus-Routen", "Schutzprojekte"], "body": "Nachhaltiger Tourismus in der Kaçkar-Region bedeutet verantwortungsvolles Reisen, das die Auswirkungen auf die Umwelt minimiert und den Nutzen für lokale Gemeinschaften maximiert. Entdecken Sie, wie Sie diese wunderschöne Region erkunden können, während Sie ihre natürliche Schönheit für zukünftige Generationen bewahren."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 8, true),
('health-wellness', 'de', 'Gesundheit & Wellness', 'Erfrischen Sie Körper und Seele in der sauberen Luft der Hochländer.', '{"header": "Finden Sie Gleichgewicht in der Natur", "bullets": ["Yoga und Meditation in der Höhe", "Atemtherapie", "Natürliche Heilungsworkshops", "Ayder-Thermalquellen", "Wellness-Retreats"], "body": "Die Kaçkar-Hochländer bieten die perfekte Umgebung für Entspannung und Heilung. Die saubere Bergluft, natürliche Thermalquellen und die Ruhe der Natur schaffen ein ideales Heiligtum, um körperliches und geistiges Gleichgewicht wiederzufinden."}', 'Heart', 'from-[#0E4542] to-[#0E4542]', 9, true),
('photography-art', 'de', 'Fotografie & Kunst', 'Erfassen Sie einzigartige Landschaften, die vom Licht der Jahreszeiten geformt werden.', '{"header": "Schaffen Sie Kunst in der Natur", "bullets": ["Saisonale Fotografierouten", "Künstlerworkshops", "Freiluftausstellungen", "Artist-in-Residence-Programme", "Natürliche Inspiration"], "body": "Die Kaçkar-Berge bieten eine unendliche Leinwand für Künstler und Fotografen. Jede Jahreszeit bringt ihre eigene Farbpalette und Emotionen mit sich, von den Wildblumen des Frühlings bis zu den verschneiten Landschaften des Winters, und schafft einzigartige künstlerische Möglichkeiten."}', 'Camera', 'from-[#0E4542] to-[#0E4542]', 10, true),
('educational-research', 'de', 'Bildungs- & Forschungstourismus', 'Ein lebendes Labor, das sich von endemischen Pflanzen bis zu Gletscherseen erstreckt.', '{"header": "Lernen Sie in einem Natürlichen Labor", "bullets": ["Biologie- und Botaniktouren", "Vogelbeobachtung", "Geologische und Gletscherforschung", "Handwerksausbildungsprogramme", "Umweltstudien"], "body": "Die Kaçkar-Region dient als natürliches Labor für Bildung und Forschung. Mit ihrer einzigartigen Biodiversität, faszinierenden geologischen Formationen und erhaltenen Ökosystemen ist es ein idealer Ort, um die Wunder der Natur zu lernen und zu entdecken."}', 'BookOpen', 'from-[#0E4542] to-[#0E4542]', 11, true),
('events-festivals', 'de', 'Veranstaltungen & Festivals', 'Nehmen Sie an lebendigen Feiern von Hochlandfestivals bis zu Teeernten teil.', '{"header": "Feiern Sie mit der Gemeinschaft", "bullets": ["Hochlandfestivals", "Horon-Tanz-Festivals", "Teeerntefestival", "Lokale Produktmärkte", "Gastronomietage"], "body": "Die Veranstaltungen und Festivals von Kaçkar sind lebendige Feiern der lokalen Kultur. Von lebendigen Hochlandfestivals bis zu traditionellen Teeernten bieten diese Veranstaltungen eine einzigartige Gelegenheit, sich in das Gemeinschaftsleben und die lokalen Traditionen zu vertiefen."}', 'Calendar', 'from-[#0E4542] to-[#0E4542]', 12, true)
ON CONFLICT (slug, locale) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  content = EXCLUDED.content,
  icon_name = EXCLUDED.icon_name,
  color_theme = EXCLUDED.color_theme,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
