-- Ensure all 9 categories exist for French and German with correct sort_order
-- This migration ensures consistency across all locales

-- First, let's check what categories exist and fix any missing ones
-- The 9 categories should be:
-- 1. nature (sort_order: 1)
-- 2. culture (sort_order: 2) 
-- 3. gastronomy (sort_order: 3)
-- 4. adventure (sort_order: 4)
-- 5. accommodation (sort_order: 5)
-- 6. transportation (sort_order: 6)
-- 7. music-dance (sort_order: 7)
-- 8. sustainable-tourism (sort_order: 8)
-- 9. health-wellness (sort_order: 9)

-- Note: photography-art, educational-research, and events-festivals are NOT in the original 9 categories
-- They were incorrectly added. The correct 9 categories are the ones above.

-- Remove any incorrect categories that shouldn't exist
DELETE FROM public.categories 
WHERE locale IN ('fr', 'de') 
AND slug IN ('photography-art', 'educational-research', 'events-festivals');

-- Ensure all 9 correct categories exist for French
INSERT INTO public.categories (slug, locale, name, description, content, icon_name, color_theme, sort_order, is_active) VALUES
('nature', 'fr', 'Nature & Aventure', 'Découvrez la puissance pure de la nature sur les sentiers qui s''élèvent des vallées vers les sommets du Kaçkar.', '{"header": "Découvrez la Beauté Sauvage des Montagnes de Kaçkar", "bullets": ["Plus de 50 lacs alpins vierges", "3,937m pic le plus haut - Kaçkar Dağı", "Flore et faune endémiques", "Forêts et prairies anciennes", "Ruisseaux de montagne cristallins"], "body": "Les montagnes de Kaçkar offrent une expérience naturelle inégalée avec leur nature sauvage vierge, leurs lacs glaciaires et leurs écosystèmes diversifiés. Du pic le plus haut à 3,937 mètres aux lacs alpins cristallins, chaque coin de cette région raconte une histoire de merveille naturelle."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 1, true),
('culture', 'fr', 'Culture & Vie Locale', 'Témoignez des histoires sincères des hauts plateaux, des manoirs et des traditions intemporelles.', '{"header": "Plongez dans les Traditions Anciennes", "bullets": ["Communautés traditionnelles Laz et Hemshin", "Anciens monastères et églises", "Artisanat et textiles locaux", "Musique et danse traditionnelles", "Vie de village authentique"], "body": "La région de Kaçkar est un trésor culturel où les traditions anciennes ont été préservées pendant des siècles. Les communautés locales Laz et Hemshin maintiennent leurs coutumes, leur langue et leur mode de vie uniques."}', 'Users', 'from-[#0E4542] to-[#0E4542]', 2, true),
('gastronomy', 'fr', 'Gastronomie & Saveurs Locales', 'Goûtez Kaçkar à travers ses produits IGP et ses saveurs locales inoubliables.', '{"header": "Savourez les Saveurs Authentiques de la Cuisine de la Mer Noire", "bullets": ["Truite de montagne fraîche et fruits de mer", "Pain de maïs traditionnel et fromages locaux", "Miel biologique et herbes de montagne", "Cérémonies de thé traditionnelles", "Vins et spiritueux locaux"], "body": "Les traditions culinaires de la région de Kaçkar reflètent le mélange unique d''influences montagnardes et côtières. Les ingrédients frais des montagnes et de la Mer Noire créent une cuisine distinctive qui a été perfectionnée au fil des générations."}', 'ForkKnife', 'from-[#0E4542] to-[#0E4542]', 3, true),
('adventure', 'fr', 'Aventure', 'Randonnée, alpinisme, tours des hauts plateaux, expériences de camping et activités d''adrénaline.', '{"header": "Partez à l''Aventure Épique en Montagne", "bullets": ["Itinéraires de randonnée multi-jours", "Alpinisme jusqu''au pic de 3,937m", "Expériences de camping en haute altitude", "Escalade et bloc", "Expéditions photographiques"], "body": "Pour les amateurs d''aventure, les montagnes de Kaçkar offrent certaines des expériences de plein air les plus difficiles et gratifiantes de Turquie. Des itinéraires de randonnée multi-jours à travers la nature sauvage vierge aux expéditions d''alpinisme vers les plus hauts sommets, la région offre des opportunités infinies d''aventures pleines d''adrénaline."}', 'Mountains', 'from-[#0E4542] to-[#0E4542]', 4, true),
('accommodation', 'fr', 'Hébergement', 'Maisons d''hôtes traditionnelles, maisons de haute altitude, sites de camping et options d''hébergement confortables.', '{"header": "Séjournez dans des Hébergements de Montagne Authentiques", "bullets": ["Maisons traditionnelles de haute altitude", "Maisons d''hôtes accueillantes avec charme local", "Sites de camping de montagne", "Lodges écologiques", "Expériences d''hébergement chez l''habitant"], "body": "Découvrez l''hospitalité authentique de montagne dans des hébergements traditionnels qui allient confort et culture locale. Des maisons d''hôtes accueillantes dans les villages de montagne aux maisons traditionnelles de haute altitude, chaque hébergement offre une perspective unique sur la vie locale."}', 'House', 'from-[#0E4542] to-[#0E4542]', 5, true),
('transportation', 'fr', 'Transport', 'Comment atteindre Kaçkar, transport local, services de transfert et informations pratiques.', '{"header": "Planifiez Votre Voyage vers les Montagnes", "bullets": ["Vols directs vers Trabzon et Rize", "Routes panoramiques depuis les grandes villes", "Services de bus et minibus locaux", "Options de transfert privé", "Accessibilité des routes de montagne"], "body": "Atteindre les montagnes de Kaçkar est plus facile que vous ne le pensez, avec plusieurs options de transport disponibles. La région est bien connectée par avion, avec des vol directs vers les aéroports de Trabzon et Rize. De là, des routes panoramiques serpentent à travers les montagnes, offrant des vues à couper le souffle en cours de route."}', 'Car', 'from-[#0E4542] to-[#0E4542]', 6, true),
('music-dance', 'fr', 'Musique & Danse', 'Ressentez l''esprit de la mer Noire avec le son du tulum et le rythme du horon.', '{"header": "Ressentez l''Esprit de la Mer Noire", "bullets": ["Variétés de danse horon", "Performances de tulum et kemençe", "Ateliers de fabrication d''instruments", "Festivals et traditions de mariage", "Célébrations culturelles vibrantes"], "body": "La musique et la danse sont au cœur de la culture de la région de Kaçkar. Le tulum et le kemençe créent des mélodies envoûtantes qui capturent l''essence de la mer Noire, tandis que les danses horon énergiques expriment la joie et l''unité de la communauté."}', 'MusicNote', 'from-[#0E4542] to-[#0E4542]', 7, true),
('sustainable-tourism', 'fr', 'Tourisme Durable', 'Un voyage de découverte qui respecte la nature et soutient la vie locale.', '{"header": "Explorez de Manière Responsable", "bullets": ["Principes de ne laisser aucune trace", "Soutien aux producteurs locaux", "Hébergement respectueux de l''environnement", "Routes d''écotourisme", "Projets de conservation"], "body": "Le tourisme durable dans la région de Kaçkar signifie voyager de manière responsable, en minimisant l''impact sur l''environnement et en maximisant les bénéfices pour les communautés locales. Découvrez comment explorer cette région magnifique tout en préservant sa beauté naturelle pour les générations futures."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 8, true),
('health-wellness', 'fr', 'Santé & Bien-être', 'Rafraîchissez votre corps et votre âme dans l''air pur des hautes terres.', '{"header": "Retrouvez l''Équilibre dans la Nature", "bullets": ["Yoga et méditation en altitude", "Thérapie respiratoire", "Ateliers de guérison naturelle", "Sources thermales d''Ayder", "Retraites de bien-être"], "body": "Les hautes terres de Kaçkar offrent l''environnement parfait pour la relaxation et la guérison. L''air pur de montagne, les sources thermales naturelles et la tranquillité de la nature créent un sanctuaire idéal pour retrouver l''équilibre physique et mental."}', 'Heart', 'from-[#0E4542] to-[#0E4542]', 9, true)
ON CONFLICT (slug, locale) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  content = EXCLUDED.content,
  icon_name = EXCLUDED.icon_name,
  color_theme = EXCLUDED.color_theme,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

-- Ensure all 9 correct categories exist for German
INSERT INTO public.categories (slug, locale, name, description, content, icon_name, color_theme, sort_order, is_active) VALUES
('nature', 'de', 'Natur & Abenteuer', 'Entdecken Sie die reine Kraft der Natur auf Pfaden, die von Tälern zu Kaçkars Gipfeln aufsteigen.', '{"header": "Entdecken Sie die Wilde Schönheit der Kaçkar-Berge", "bullets": ["Über 50 unberührte alpine Seen", "3,937m höchster Gipfel - Kaçkar Dağı", "Endemische Flora und Fauna", "Uralte Wälder und Wiesen", "Kristallklare Gebirgsbäche"], "body": "Die Kaçkar-Berge bieten ein unvergleichliches Naturerlebnis mit ihrer unberührten Wildnis, Gletscherseen und vielfältigen Ökosystemen. Vom höchsten Gipfel auf 3,937 Metern bis zu den kristallklaren alpinen Seen erzählt jeder Winkel dieser Region eine Geschichte natürlicher Wunder."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 1, true),
('culture', 'de', 'Kultur & Lokales Leben', 'Erleben Sie die herzlichen Geschichten der Hochländer, Herrenhäuser und zeitlosen Traditionen.', '{"header": "Tauchen Sie ein in Alte Traditionen", "bullets": ["Traditionelle Laz- und Hemshin-Gemeinschaften", "Uralte Klöster und Kirchen", "Lokales Handwerk und Textilien", "Traditionelle Musik und Tanz", "Authentisches Dorfleben"], "body": "Die Kaçkar-Region ist ein kultureller Schatz, in dem alte Traditionen über Jahrhunderte bewahrt wurden. Die lokalen Laz- und Hemshin-Gemeinschaften bewahren ihre einzigartigen Bräuche, Sprache und Lebensweise."}', 'Users', 'from-[#0E4542] to-[#0E4542]', 2, true),
('gastronomy', 'de', 'Gastronomie & Lokale Aromen', 'Schmecken Sie Kaçkar durch seine g.U.-Produkte und unvergessliche lokale Aromen.', '{"header": "Genießen Sie die Authentischen Aromen der Schwarzmeer-Küche", "bullets": ["Frische Bergforelle und Meeresfrüchte", "Traditionelles Maisbrot und lokale Käsesorten", "Bio-Honig und Bergkräuter", "Traditionelle Teezeremonien", "Lokale Weine und Spirituosen"], "body": "Die kulinarischen Traditionen der Kaçkar-Region spiegeln die einzigartige Mischung aus Berg- und Küsteneinflüssen wider. Frische Zutaten aus den Bergen und dem Schwarzen Meer schaffen eine unverwechselbare Küche, die über Generationen perfektioniert wurde."}', 'ForkKnife', 'from-[#0E4542] to-[#0E4542]', 3, true),
('adventure', 'de', 'Abenteuer', 'Wandern, Bergsteigen, Hochlandtouren, Camping-Erlebnisse und Adrenalin-Aktivitäten.', '{"header": "Begeben Sie sich auf Epische Bergabenteuer", "bullets": ["Mehrtägige Wanderrouten", "Bergsteigen zum 3,937m Gipfel", "Hochland-Camping-Erlebnisse", "Klettern und Bouldern", "Fotografie-Expeditionen"], "body": "Für Abenteuerlustige bieten die Kaçkar-Berge einige der herausforderndsten und lohnendsten Outdoor-Erlebnisse der Türkei. Von mehrtägigen Wanderrouten durch unberührte Wildnis bis hin zu Bergsteiger-Expeditionen zu den höchsten Gipfeln bietet die Region endlose Möglichkeiten für adrenalingeladene Abenteuer."}', 'Mountains', 'from-[#0E4542] to-[#0E4542]', 4, true),
('accommodation', 'de', 'Unterkunft', 'Traditionelle Gästehäuser, Hochlandhäuser, Campingplätze und komfortable Unterkunftsmöglichkeiten.', '{"header": "Übernachten Sie in Authentischen Bergunterkünften", "bullets": ["Traditionelle Hochlandhäuser", "Gemütliche Gästehäuser mit lokalem Charme", "Berg-Campingplätze", "Umweltfreundliche Lodges", "Homestay-Erlebnisse"], "body": "Erleben Sie authentische Berggastfreundschaft in traditionellen Unterkünften, die Komfort mit lokaler Kultur verbinden. Von gemütlichen Gästehäusern in Bergdörfern bis hin zu traditionellen Hochlandhäusern bietet jede Unterkunft eine einzigartige Perspektive auf das lokale Leben."}', 'House', 'from-[#0E4542] to-[#0E4542]', 5, true),
('transportation', 'de', 'Transport', 'Wie man Kaçkar erreicht, lokaler Transport, Transferdienste und praktische Informationen.', '{"header": "Planen Sie Ihre Reise in die Berge", "bullets": ["Direktflüge nach Trabzon und Rize", "Panoramastraßen von Großstädten", "Lokale Bus- und Minibus-Services", "Private Transfer-Optionen", "Gebirgsstraßen-Zugänglichkeit"], "body": "Die Kaçkar-Berge zu erreichen ist einfacher als Sie denken, mit mehreren Transportoptionen verfügbar. Die Region ist gut per Flugzeug verbunden, mit Direktflügen zu den Flughäfen von Trabzon und Rize. Von dort aus winden sich malerische Straßen durch die Berge und bieten atemberaubende Aussichten unterwegs."}', 'Car', 'from-[#0E4542] to-[#0E4542]', 6, true),
('music-dance', 'de', 'Musik & Tanz', 'Fühlen Sie den Geist des Schwarzen Meeres mit dem Klang des Tulum und dem Rhythmus des Horon.', '{"header": "Fühlen Sie den Geist des Schwarzen Meeres", "bullets": ["Horon-Tanz-Variationen", "Tulum- und Kemençe-Aufführungen", "Instrumentenbau-Workshops", "Festivals und Hochzeitstraditionen", "Lebendige kulturelle Feiern"], "body": "Musik und Tanz stehen im Herzen der Kultur der Kaçkar-Region. Tulum und Kemençe schaffen bezaubernde Melodien, die das Wesen des Schwarzen Meeres einfangen, während die energischen Horon-Tänze die Freude und Einheit der Gemeinschaft ausdrücken."}', 'MusicNote', 'from-[#0E4542] to-[#0E4542]', 7, true),
('sustainable-tourism', 'de', 'Nachhaltiger Tourismus', 'Eine Entdeckungsreise, die die Natur respektiert und das lokale Leben unterstützt.', '{"header": "Erkunden Sie Verantwortungsvoll", "bullets": ["Leave-No-Trace-Prinzipien", "Unterstützung lokaler Produzenten", "Umweltfreundliche Unterkünfte", "Ökotourismus-Routen", "Schutzprojekte"], "body": "Nachhaltiger Tourismus in der Kaçkar-Region bedeutet verantwortungsvolles Reisen, das die Auswirkungen auf die Umwelt minimiert und den Nutzen für lokale Gemeinschaften maximiert. Entdecken Sie, wie Sie diese wunderschöne Region erkunden können, während Sie ihre natürliche Schönheit für zukünftige Generationen bewahren."}', 'Leaf', 'from-[#0E4542] to-[#0E4542]', 8, true),
('health-wellness', 'de', 'Gesundheit & Wellness', 'Erfrischen Sie Körper und Seele in der sauberen Luft der Hochländer.', '{"header": "Finden Sie Gleichgewicht in der Natur", "bullets": ["Yoga und Meditation in der Höhe", "Atemtherapie", "Natürliche Heilungsworkshops", "Ayder-Thermalquellen", "Wellness-Retreats"], "body": "Die Kaçkar-Hochländer bieten die perfekte Umgebung für Entspannung und Heilung. Die saubere Bergluft, natürliche Thermalquellen und die Ruhe der Natur schaffen ein ideales Heiligtum, um körperliches und geistiges Gleichgewicht wiederzufinden."}', 'Heart', 'from-[#0E4542] to-[#0E4542]', 9, true)
ON CONFLICT (slug, locale) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  content = EXCLUDED.content,
  icon_name = EXCLUDED.icon_name,
  color_theme = EXCLUDED.color_theme,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
